//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FalTurleri
    {
        public int Id_Fal { get; set; }
        public string fal_isim { get; set; }
        public int fal_credit { get; set; }
        public string fal_kategori { get; set; }
    }
}
