//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public System.DateTime dob { get; set; }
        public string pinCode { get; set; }
        public Nullable<int> credit { get; set; }
        public string realName { get; set; }
        public string realSurName { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
        public Nullable<System.DateTime> LastSignedIn { get; set; }
        public string LastSignInLocation { get; set; }
    }
}
